[tool.isort]
line_length = 119
combine_star = true
multi_line_output = 3
order_by_type = true
lines_between_types = 1
include_trailing_comma = true
sections=["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
skip = ["scripts"]

[tool.black]
line-length = 119
target-version = ['py36']
skip-string-normalization = true
